### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by Taraman17** [Taraman17/hacs-homee#10]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
translate the strings in Homee Integration to German.

**Describe alternatives you've considered**
None - really.

**Additional context**
As Homee is a product that is used in Germany a lot, I think it would be a good thing to a have a german translation

**Comment by LuiTK** [comment]
I have created a German translation file.
[de.json](https://github.com/Taraman17/hacs-homee/files/13189765/de.json)

**Comment by Taraman17** [comment]
Vielen Dank!!!

**Comment by Taraman17** [comment]
Closed with Release 2.7.0
