### ISSUE TITLE
ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 

### ISSUE THREAD

**Issue by Wesie** [Taraman17/hacs-homee#28]
- [ ] I have a question.
- [ ] A feature does not work as expected.
- [X] I found a bug (see error log below).

## Version
- newest version

## Detailed description
The upgrade process are startet via the upgrade button in HA. After that a restart of HA was done the error mesage occurred.

HA is running in a docker (PI4). In this moment only homee is connectet to log the statistik for the the solar / Grid power. 

## Error log
2023-11-05 18:29:44.857 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform homee.alarm_control_panel: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).

**Comment by Taraman17** [comment]
To assess the severity of this error - does this prevent Homee from working in HA?

**Comment by Wesie** [comment]
The rest looks like normal. In this moment I collect only the different messages from the sensors and actors....HA did not act active any action.

**Comment by Taraman17** [comment]
Which version of HA Core are you running?

It seems this import was  moved recently - as fas as I can see only with 2023.11.1

**Comment by Taraman17** [comment]
Then you should check, why you don't get the update information - 2023.11.1 is latest.

**Comment by Wesie** [comment]
The repository isn't updated in this moment. I don't want change to another repository because I need the collected data in history and future for statistical reasons. So I must wait, that the paket received an update ...

**Comment by Taraman17** [comment]
Hi,
since you have opened new Issues with one of the latest HA releases, I assume you use this now.
Is this issue solved with that?

**Comment by Wesie** [comment]
Hi, I've updated the full RPI, OS, HA and HACS and hass-homee. The reported message in the sytem log is no more occurred.  So the issue could be close as done . Thx for your help
