### ISSUE TITLE
Automatic pull request to homee for status update of garage door

### ISSUE THREAD

**Issue by Taraman17** [Taraman17/hacs-homee#8]
**Is your feature request related to a problem? Please describe.**
 
 The latest fixes for the garage door are awesome. Thank you very much @Taraman17 for your work. I've encountered one problem with my hörmann garage door series4. After using a remote control to control the garage door, the state of the garage position is not updated inside the app itself. (a bug homee just doesn't fix..) therefore I've to go inside the official app to click on the three dots in the upper right corner from the garage door to use "Werte aktualisieren" (update values) to let homee pull the latest status of the garage door.
 
 **Describe the solution you'd like** It would be awesome if hass would automatically request the "update values" every x minutes to solve the problem.
 
 **Describe alternatives you've considered** Expose the "update values" as a button to solve the problem.
 
 **Additional context** Is it only my version, or do you have the same problem as me @Taraman17 @godza ?
 
 PS: I hope someone hacks the bisecure from hörmann for local usage of their garage doors

**Comment by godza** [comment]
Hi, @Taraman17 same thing happens to me. If I use remote or wired keys, homee get's out of sync with the real state of the garage door, and that also shows in the home assistant.

Periodic refresh would be a good workaround if Hormann or homee will not fix the bug.

**Comment by Taraman17** [comment]
I'm still trying to figure out how to best query homee for an update without needing to get all data.

**Comment by Macway44** [comment]
I don't have this problem. Everything works perfectly with my 2 garage doors (supramatic 4).
Congratulations and thank you very much.

**Comment by Taraman17** [comment]
I just prepared a beta release with a new service, that allows to update homee entities or devices. You can then create an automation to update regularly.
Please test and see if it works for you. @Pr0mises  @godza

See https://github.com/Taraman17/hacs-homee/blob/master/howto_beta.md for how to install the beta.

**Comment by godza** [comment]
Thank you Taraman17, this service sounds like a great solution. Completely optional, but yet available for people who need it.

Unfortunately i cannot install the beta release as even with "beta" versions included i only see non-beta ones: 2.5.1, 2.5.0, 2.4.0, 2.3.3, 2.3.2, master.

I tried toggling beta versions switch on and off but with the same results. I also clicked the "Update information" but had the same results

**Comment by godza** [comment]
Ouch, i seem to be still on old repository, i will switch to this one now.

**Comment by godza** [comment]
Just to confirm, i should create an automation that calls a service "homee: Update Entity" with entities of my homee (Hormann) devices?

If so, i did that and will let you know how it works after i test it next couple of days.

Thanks

**Comment by Taraman17** [comment]
Exactly.
I'm curious.

**Comment by Pr0mises** [comment]
I did try it with my hörmann garage door series4 but after calling the service nothing happens. I didnt't check the logs yet, will do later.
I did find a new option in homee tho. It's under Devices -> Device 3 dots -> edit -> scroll down to configuration -> polling interval -> set >0.
The default polling interval is 0 (disabled, great coders...) per default. 1 is min value. Now it get's pulled every minute.

**Comment by Taraman17** [comment]
The idea with the polling interval is also good.
It is disabled per default, because the Homee data is expected to be pushed and polled. So there was no need to have extra traffic being caused.
Maybe it will also be an idea to change that for certain devices.

**Comment by godza** [comment]
Preliminary report is good. I did not stumble upon a single instance where homee state is different than real state. I configured automation to be polled every minute and i'm really happy with my hacs-homee integration.

Great job Taraman17!

**Comment by Taraman17** [comment]
@Pr0mises: The idea with the polling interval is also good.
It is disabled per default, because the Homee data is expected to be pushed and polled. So there was no need to have extra traffic being caused.
Maybe it will also be an idea to change that for certain devices.

@godza: Great, I will prepare the production release the next days.

**Comment by Taraman17** [comment]
Closed with Release 2.7.0
